#!/bin/bash
# ╔══════════════════════════════════════════╗
# ║   OSINT BBW TOOL v2.0 - Rayquaza        ║
# ╚══════════════════════════════════════════╝
PROJEKTORDNER="/Users/macbookausmnorden/Documents/OSINT-TOOL-BBW"
cd "$PROJEKTORDNER"
source venv/bin/activate
python3 main.py "$@"
